version: '3'

version: '3'
services:
  emubt-sdk:
    build: .
    privileged: true
    network_mode: host
    container_name: pyqt-dev-env
    tty: true
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/machine-id:/etc/machine-id
      - ./shared:/home/root
      - ./emu_bt_r:/home/root/emu_bt_r  # link source file here
    devices:
      - /dev/snd